- name: install apache and php (Ubuntu)
  tags: apache,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start apache
  tags: apache,start_apache,service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change admin email-address
  tags: apache,ami,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin ozirichigozie@gmail.com
  when: ansible_distribution == "Amazon"
  notify: restart_apache

- name: copy default website html file
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
